using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Spieniarka4._0
{
    public class SummaryFileColumnNames
    {
        public const string Pusta_0 = "";
        public const string Wersja = "Wersja";
        public const string Maszyna = "Maszyna";
        public const string Data_poczatek = "Data_poczatek";
        public const string Data_koniec = "Data_koniec";
        public const string Nr_zlecenia = "Nr_zlecenia";
        public const string MPU = "MPU";
        public const string Nr_recepty = "Nr_recepty";
        public const string Producent = "Producent";
        public const string Typ = "Typ";
        public const string Gestosc_zadana = "Gestosc_zadana";
        public const string Gestosc_min = "Gestosc_min";
        public const string Gestosc_srednia = "Gestosc_srednia";
        public const string Gestosc_max = "Gestosc_max";
        public const string Ilosc_zad_Surowca = "Ilosc_zad_Surowca";
        public const string Ilosc_rzecz_Surowca = "Ilosc_rzecz_Surowca";
        public const string Ilosc_zad_partii = "Ilosc_zad_partii";
        public const string Ilosc_rzecz_partii = "Ilosc_rzecz_partii";
        public const string Operator = "Operator";
        public const string Komora = "Komora";
        public const string Nr_LOT = "Nr_LOT";
        public const string Material = "Material";
        public const string box = "box";
        public const string ID = "ID";
        public const string Czas_cyklu = "Czas_cyklu";
        public const string Silos_0 = "Silos_0";
        public const string Silos_1 = "Silos_1";
        public const string Silos_2 = "Silos_2";
        public const string Silos_3 = "Silos_3";
        public const string Silos_4 = "Silos_4";
        public const string Silos_5 = "Silos_5";
        public const string Silos_6 = "Silos_6";
        public const string Silos_7 = "Silos_7";
        public const string Silos_8 = "Silos_8";
        public const string Silos_9 = "Silos_9";
        public const string Czas_napel = "Czas_napel";
        public const string Czas_podgrz_wst = "Czas_podgrz_wst";
        public const string Czas_pary = "Czas_pary";
        public const string Czas_prozni = "Czas_prozni";
        public const string Czas_oprozniania = "Czas_oprozniania";
        public const string Wyl_poziomu = "Wyl_poziomu";
        public const string Bajpas = "Bajpas";
        public const string Wartosc_nawazki = "Wartosc_nawazki";
        public const string Cisn_pary = "Cisn_pary";
        public const string T_pary = "T_pary";
        public const string Predkosc_mieszadla = "Predkosc_mieszadla";
        public const string Predkosc_sluzy_lopatk = "Predkosc_sluzy_lopatk";
        public const string Predkosc_oproz = "Predkosc_oproz";
        public const string Czas_pary_Auto = "Czas_pary_Auto";
        public const string Min_T_kotla = "Min_T_kotla";
        public const string Cisn_odpow = "Cisn_odpow";
        public const string Czas_odpow = "Czas_odpow";
        public const string Czas_nadmuchu_kotla = "Czas_nadmuchu_kotla";
        public const string Czas_zakonczenia_parowania = "Czas_zakonczenia_parowania";
        public const string wyladunek_bez_prozni = "wyladunek_bez_prozni";
        public const string wyladunek_z_proznia = "wyladunek_z_proznia";
        public const string Pusta1 = "";
        public const string Pusta2 = "";
        public const string Jedn_gestosci = "Jedn_gestosci";
        public const string Jedn_cisn = "Jedn_cisn";
        public const string Jedn_temp = "Jedn_temp";
        public const string Jedn_wagi = "Jedn_wagi";
        public const string Parowanie_posrednie = "Parowanie_posrednie";
        public const string Czas_SSS1 = "Czas_SSS1";
        public const string Bypass_SSS1 = "Bypass_SSS1";
        public const string Cisn_SSS1 = "Cisn_SSS1";
        public const string T_SSS1 = "T_SSS1";
        public const string Mieszadlo_SSS1 = "Mieszadlo_SSS1";
        public const string Czas_SSS2 = "Czas_SSS2";
        public const string Bypass_SSS2 = "Bypass_SSS2";
        public const string Cisn_SSS2 = "Cisn_SSS2";
        public const string T_SSS2 = "T_SSS2";
        public const string Mieszadlo_SSS2 = "Mieszadlo_SSS2";
        public const string Czas_SSS3 = "Czas_SSS3";
        public const string Bypass_SSS3 = "Bypass_SSS3";
        public const string Cisn_SSS3 = "Cisn_SSS3";
        public const string T_SSS3 = "T_SSS3";
        public const string Mieszadlo_SSS3 = "Mieszadlo_SSS3";
        public const string Czas_SSS4 = "Czas_SSS4";
        public const string Bypas_SSS4 = "Bypas_SSS4";
        public const string Cisn_SSS4 = "Cisn_SSS4";
        public const string T_SSS4 = "T_SSS4";
        public const string Mieszadlo_SSS4 = "Mieszadlo_SSS4";
        public const string Czas_SSS5 = "Czas_SSS5";
        public const string Bypass_SSS5 = "Bypass_SSS5";
        public const string Cisn_SSS5 = "Cisn_SSS5";
        public const string T_SSS5 = "T_SSS5";
        public const string Mieszadlo_SSS5 = "Mieszadlo_SSS5";
        public const string Klapa_suszarki = "Klapa_suszarki";
        public const string Klapa_transportu = "Klapa_transportu";
        public const string T_grzalki = "T_grzalki";
        public const string Nr_fab = "Nr_fab";
        public const string Opoznienie_orozniania_suszarki = "Opoznienie_orozniania_suszarki";
    }
}
